name: Test Screenshot Comparison

on:
  release:
    types:
      - published

  workflow_dispatch:
    inputs:
      test_url:
        description: 'URL to test screenshot comparison with'
        required: true
        type: string
        default: 'https://example.com'
      threshold:
        description: 'Difference threshold percentage'
        required: false
        type: number
        default: 20
      environment:
        description: 'Environment name'
        required: false
        type: string
        default: 'test-environment'
      contract:
        description: 'Contract name'
        required: false
        type: string
        default: 'test-contract'
      build_mode:
        description: 'Build mode'
        required: false
        type: string
        default: 'Test'

jobs:
  screenshot-comparison:
    strategy:
      matrix:
        contract:
          - test
        include:
          - contract: test
            deploy_url: https://jac2759.github.io/Release-comparison/
            environment: test-environment
            build_mode: Test
    uses: ./.github/workflows/screenshot-comparison-advanced.yml
    secrets: inherit
    with:
      deploy_url: ${{ matrix.deploy_url }}
      environment: ${{ matrix.environment }}
      contract_name: ${{ matrix.contract }}
      build_mode: ${{ matrix.build_mode }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
      threshold: 20
