name: Test Screenshot Comparison

on:
  push:
    branches: [ main ]
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      threshold:
        description: 'Difference threshold percentage'
        required: false
        type: number
        default: 20
      build_mode:
        description: 'Build mode'
        required: false
        type: string
        default: 'Test'

jobs:
  screenshot-comparison:
    strategy:
      matrix:
        contract:
          - test
        include:
          - contract: test
            deploy_url: https://jac2759.github.io/Release-comparison/
            environment: test-environment
            build_mode: Test
    uses: ./.github/workflows/screenshot-comparison-advanced.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      deploy_url: ${{ matrix.deploy_url }}
      environment: ${{ matrix.environment }}
      contract_name: ${{ matrix.contract }}
      build_mode: ${{ inputs.build_mode }}
      threshold: ${{ inputs.threshold }}
# Updated Mon Sep 29 10:27:15 BST 2025
